### ISSUE TITLE
add docs on the geometry (specifically for stroke tessellation )

### ISSUE THREAD

**Issue by idobenamram** [Lichtso/contrast_renderer#1]
hey, this looks amazing.
I am trying to implement something similar (for learning purposes) and I was wondering,
if there are any docs/tutorials/papers/etc you can point me to for the stroke tessellation algorithm you use.

I tried reading the code and playing around with it by just creating a line and seeing what vertices are created and how (using stroke).
What I found hard to understand was the part where you use regressive_product to calculate the tangent on the bezier control points.
I am a noob when it comes to geometric algebra and would love to understand how you calculate the vertices.

Thank you so much,
and great work!

**Comment by Lichtso** [comment]
The nice thing about geometric algebra is, that you can look at the data types involved in operations to guess what they are doing. In the case of [the regressive product of two (control) points](https://docs.rs/geometric_algebra/latest/geometric_algebra/ppga2d/union.Point.html#impl-RegressiveProduct%3CPoint%3E-for-Point), it connects them into a line (2D plane), which happens to be the tangent. That is because for bezier curves the partial derivative at their start and end is the line segments between their control points. For all other points in between (0 < parameter < 1) I use the [power basis](http://graphics.cs.ucdavis.edu/education/CAGDNotes/Matrix-Cubic-Bezier-Curve/Matrix-Cubic-Bezier-Curve.html), which is just a fanzy algebraic way of formulating polynomial curves as a matrix to speed up the calculation.

**Comment by idobenamram** [comment]
i see so its just a fancy way of calculating the tangent? and I need the tangent to calculate the normal?

Could we just have used the derivative of the curve?
thank you so much!

**Comment by Lichtso** [comment]
Yes, parameter=> tangent => normal => offset curve.

The derivative of the curve is the direction and length of the tangent. The tangent additionally has information about its location (the point at which it touches the curve).
